[package]
name = "jude"
version = "0.1.0"
authors = ["solomatovs <solomatovs@gmail.com>"]
edition = "2021"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = { version = "0.8.3" }
thiserror = "1.0.59"
