[package]
name = "jude"
version = "0.1.0"
authors = ["solomatovs <solomatovs@gmail.com>"]
edition = "2021"
license = "mim"
description = ""
homepage = "https://github.com/solomatovs/jude"
repository = "https://github.com/solomatovs/jude"
readme = "README.md"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = { version = "0.8.3" }
